vim.pack.add({
    "https://github.com/ntpeters/vim-better-whitespace",
    "https://github.com/tpope/vim-vinegar",
    "https://github.com/tpope/vim-surround",
    "https://github.com/tpope/vim-repeat",
    "https://github.com/neovim/nvim-lspconfig",
    "https://github.com/challenger-deep-theme/vim",
})
vim.cmd.colorscheme("challenger_deep")
